### ISSUE TITLE
Q: About Streamlining internal and external usage of various names for operations

### ISSUE THREAD

**Issue by modellking** [derElias/udvide-Server#26]
Currrently CRUD to VFC accepts A LOT of synonmous methods...
Do we want to use a short form like C for Create U for Udate etc.,
3 char short form,
CRUD Create... or
Vuforias Naming sceme (similar to HTTP) Post,...
or should we use something else?

Further: I allow any Upper-Lowercase combination. while i do not want to change that for the VFC API adapter we should define a standart...

**Comment by modellking** [comment]
i personally like camelCase for the casing question.

**Comment by derElias** [comment]
camelCase sounds fine and its my personal favourite too, but I would approve anything else then short, because it makes the code less readable

**Comment by Speednik2** [comment]
Personally i use camelCase too, so im fine with it!

**Comment by modellking** [comment]
i'd really apprechiate comments which include ideas or opinions about using Create, Read, Update, Delete vs Post Get Put Delete

**Comment by modellking** [comment]
Based on the input I'll go with camelCase and CRUD
