### ISSUE TITLE
Q: How should we treat too large images

### ISSUE THREAD

**Issue by modellking** [derElias/udvide-Server#27]
VWS has a limit of 2 MB for images.
if an image exeedes this limit we should try to reduce its filesize by cropping, downscaling and compression
while cropping is fairly straight forward
the balance between downscaling and compression is not!

Suggestions?

**Comment by derElias** [comment]
We may encounter different problems or bugs acording to solution we choose:
with cropping our position of our content relativ to the marker could be wrong or the content to small etc.
with scaling the marker may wont be recognised at all

**Comment by modellking** [comment]
we settled at setting to 95% and croping and if still too large we scale the image down by .5 each side
(expect commit)
