### ISSUE TITLE
Issue with PHPstorm

### ISSUE THREAD

**Issue by modellking** [derElias/udvide-Server#34]
Ok we got a major thing...
Turns out PHPstorms built in server isn't capable of using the $_POST array wich is essential to our Asynchronous dataexchange (AJAX)

See bug https://youtrack.jetbrains.com/issue/WI-30168

Common suggestions seem to be:

* Installing a seperate Apache for testing and remapping phpStorm
* Just leaving the small part of AJAX exchange untested after confirming basic functionality on production server

**Comment by derElias** [comment]
we will leave it untested, since the affected part is only a few lines of code. 
Also we can run some tests witin the live server instead of the buildin-server, before we release the final product.

**Comment by modellking** [comment]
since PHPStorms internal Webserver kind of gave up on supporting HTTP/Response2 we switched solutions.
